cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:id>/', views.cart_add, name='cart_add'),
    path('remove/<int:id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail')
]

coupons/urls.py
from django.urls import path

from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply')
]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.create_order, name='create_order'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    # path('<slug:category_slug>/', views.product_list_view, name='product_list_by_slug'),
    path('<slug:category_slug>/', views.ProductListView.as_view(), name='product_list_by_slug'),
    # path('<int:id>/<slug:slug>/', views.product_detail_view, name='product_detail'),
    path('<int:id>/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    # path('', views.product_list_view, name='product_list'),

    path('', views.ProductListView.as_view(), name='product_list'),
]

webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('coupons/', include('coupons.urls')),
    path('', include('shop.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=100,
                                  label="Quantity",)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from shop.models import Product


@require_POST
def cart_add(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    form = CartAddProductForm(request.POST)
    cd = {}
    if form.is_valid():
        cd = form.cleaned_data
    else:
        cd['quantity'] = 1
        cd['override'] = False
    cart.add(product=product,
             quantity=cd['quantity'],
             override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
                                'quantity': item['quantity'],
                                'override': True
                            })
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Cart
{% endblock %}

{% block content %}
    {% if not cart %}

    <div class="d-flex justify-content-center">
        <h1>You cart is empty</h1>
    </div>
    <div class="d-flex justify-content-center">
        <h3><a href="{% url 'shop:product_list' %}">Browse the site</a></h3>
    </div>
    {% else %}
        <table class="table table-dark table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Picture</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th></th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                    <tr>
                        <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>

                        <td><img class="img-thumbnail crop-small" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"></td>

                        <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method='post'>
                                {% csrf_token %}
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                                <input class="btn btn-primary" type="submit" value="Update">
                            </form>
                        </td>
                        <td>{{ product.price }}</td>
                        <td>
                            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                {% csrf_token %}
                                <input class='btn btn-danger' type="submit" value="Delete">
                            </form>
                        </td>
                        <td>
                            {{ item.total_price }} RUB
                        </td>
                    </tr>
                    {% endwith %}
                {% endfor %}
                {% if cart.coupon %}
                    <tr class="subtotal">
                        <td>Subtotal</td>
                        <td colspan="4"></td>
                        <td>{{ cart.get_total_price }} RUB</td>
                    </tr>
                    <tr>
                        <td>
                            "{{ cart.coupon.code }}" coupon
                            ({{ cart.coupon.discount }}% off)
                        </td>
                        <td colspan="4"></td>
                        <td>- {{ cart.get_discount|floatformat:2 }} RUB</td>
                    </tr>
                    <tr>
                        <td>Summary</td>
                        <td colspan="4"></td>
                        <td>{{ cart.get_total_price_after_discount|floatformat:2 }} RUB</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
        <p>Apply a coupon:</p>
        <form action="{% url 'coupons:apply' %}" method="post">
            {% csrf_token %}
            {{ coupon_apply_form }}
            <input class="btn btn-success" type="submit" value="Apply">
        </form>
        <div class="d-flex justify-content-center mb-3 mt-3">
            <a class="btn btn-secondary me-2" href="{% url 'shop:product_list' %}">Continue shopping</a>
            <a class="btn btn-primary" href="{% url 'order:create_order' %}">Checkout</a>
        </div>
    {% endif %}
{% endblock %}