cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:id>/', views.cart_add, name='cart_add'),
    path('remove/<int:id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail')
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    # path('<slug:category_slug>/', views.product_list_view, name='product_list_by_slug'),
    path('<slug:category_slug>/', views.ProductListView.as_view(), name='product_list_by_slug'),
    # path('<int:id>/<slug:slug>/', views.product_detail_view, name='product_detail'),
    path('<int:id>/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    # path('', views.product_list_view, name='product_list'),

    path('', views.ProductListView.as_view(), name='product_list'),
]

webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('coupons/', include('coupons.urls')),
    path('', include('shop.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.urls import reverse
from django.core.cache import cache
from django.conf import settings

import os
from shutil import copy


class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.title


@receiver(post_save, sender=Category)
@receiver(post_delete, sender=Category)
def categories_cache_clear(sender, **kwargs):
    cache.delete('categories_list')


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100)
    description = models.TextField(max_length=1000, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    image = models.ImageField(blank=True, upload_to='products')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


#  Attempt to avoid heroku media files trouble

#     def static_image(self):
#         if self.image:
#             path = os.path.join('img', self.image.name.split('/')[1])
#             return path
#
#
# @receiver(post_save, sender=Product)
# def media_image_to_static(sender, instance, **kwargs):
#     path = instance.image.path
#     name = path.split('/')[-1]
#     copy(path, os.path.join(settings.BASE_DIR, f'static/img/{name}'))


class SpecificationsItem(models.Model):
    product = models.ForeignKey(Product, related_name='specs', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Product, Category


class ProductListView(ListView):
    model = Product
    paginate_by = 12
    template_name = 'product/list.html'
    context_object_name = 'products'
    ordering = ['-updated']

    def get_queryset(self, *args, **kwargs):
        try:
            category = Category.objects.filter(slug=self.kwargs['category_slug']).first()
            products = Product.objects.filter(available=True, category=category)
        except KeyError:
            products = Product.objects.filter(available=True)
        return products
        # return products.order_by('-updated')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['category'] = self.kwargs['category_slug']
        except KeyError:
            pass
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/detail.html'
    context_object_name = 'product'

    def get_queryset(self, *args, **kwargs):
        product = Product.objects.filter(slug=self.kwargs['slug'], id=self.kwargs['id'])
        return product.order_by('-updated')

shop/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load cache %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - Donts's E-Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body style="background-color: rgb(24, 26, 27);" class="text-white">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'shop:product_list' %}">Donts's E-Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item dropdown">
          <a class="btn btn-secondary dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu dropdown-menu-dark text-white" aria-labelledby="navbarDropdown">
              {% cache 500 sidebar %}
                {% for cat in categories_list %}
                    <li><a class="dropdown-item" href="{% url 'shop:product_list_by_slug' cat.slug %}">{{ cat.title }}</a></li>
                {% endfor %}
            {% endcache %}
          </ul>
        </li>
      </ul>
      <li class="d-flex">
        <a class="btn btn-success me-2" aria-current="page" href="{% url 'cart:cart_detail' %}">{{ cart|length }} items in your cart</a>
      </li>
    </div>
  </div>
</nav>

<div class="container mb-2 ps-3 pe-3 pb-2">
    {% block content %}
    {% endblock %}
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
</body>
</html>